# Generated by Django 4.2.5 on 2024-04-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ridelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
